# Project information
site_name: Software Engineering
use_directory_urls: true

# Repository
# repo_name: Cyberspace-Explore
# repo_url: https://github.com/AvenMay/cyberspace-explore

# Configuration
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/application-brackets
    # repo: fontawesome/brands/github
  palette:
    - scheme: default    # 浅色模式
      # primary: indigo
      # accent: indigo
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: 切换到深色模式
    - scheme: slate      # 深色模式
      # primary: indigo
      # accent: indigo
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono

  toc:
    on_page: true
    depth: 5


# Page tree
nav:

  - Programming:
    - programming/index.md
    - Preparation:
      - programming/preparation/ranking-analysis.md
      - programming/preparation/encoding.md
      - programming/preparation/interfaces.md
      - programming/preparation/best-practices.md
    - Basic-Tools:
      - programming/basic-tools/editor.md
      - programming/basic-tools/git.md
    - Python:
      - programming/python/index.md
      - programming/python/use-cases.md
    - JavaScript:
      - programming/javascript/index.md
      - programming/javascript/use-cases.md
    - C:
      - programming/c/index.md
      - programming/c/use-cases.md
    - Go:
      - programming/go/index.md
      - programming/go/use-cases.md
    - Rust:
      - programming/rust/index.md
      - programming/rust/use-cases.md
    - Enterprise:
      - Java:
        - programming/java/index.md
        - programming/java/use-cases.md
      - C#:
        - programming/csharp/index.md
        - programming/csharp/use-cases.md
      - C++:
        - programming/cpp/index.md
        - programming/cpp/use-cases.md
    - Scripts:
      - programming/scripts/lua.md
      - programming/scripts/perl.md
      - programming/scripts/ruby.md
      - programming/scripts/php.md
    - Assembly:
        - programming/assembly/index.md
        - programming/assembly/x86.md
        - programming/assembly/arm.md
    - Platforms:
      - programming/platforms/swift.md
      - programming/platforms/kotlin.md 
    - Parallel:
      - programming/parallel/index.md

  - Databases:
    - databases/index.md
    - RDBMS:
      - databases/rdbms/index.md
      - databases/rdbms/postgresql.md
      - databases/rdbms/sqlite.md
      - databases/rdbms/mysql.md
      - databases/rdbms/oracle.md
      - databases/rdbms/sql-server.md
    - Key-Value:
      - databases/key-value/redis.md
      - databases/key-value/memcached.md
    - Document:
      - databases/document/mongodb.md
    - Search-Engine:
      - databases/search-engine/elasticsearch.md
      - databases/search-engine/lucene.md
      - databases/search-engine/solr.md
      - databases/search-engine/splunk.md
    - Graph:
      - databases/graph/neo4j.md
    - Time-Series:
      - databases/time-series/influxdb.md
      - databases/time-series/prometheus.md
    - Wide-Column:
      - databases/wide-column/cassandra.md
      - databases/wide-column/hbase.md

  - Operating-System:
      - operating-system/index.md
      - Basic-Tools:
        - operating-system/basic-tools/terminal.md
        - operating-system/basic-tools/ssh.md
        - operating-system/basic-tools/multiplexer.md
      - Unix-like:
        - operating-system/unix-like/index.md
      - GNU/Linux:
        - operating-system/gnu-linux/index.md
        - operating-system/gnu-linux/shell.md
        - operating-system/gnu-linux/gui.md
        - operating-system/gnu-linux/syscall.md
        - operating-system/gnu-linux/kernel.md
        - operating-system/gnu-linux/debian.md
        - operating-system/gnu-linux/rhel.md
        - More-Distrs:
          - operating-system/gnu-linux/distr/arch.md
          - operating-system/gnu-linux/distr/alpine.md
          - operating-system/gnu-linux/distr/suse.md
      - Windows:
        - operating-system/windows/index.md
        - operating-system/windows/powershell.md
        - operating-system/windows/gui.md
        - operating-system/windows/windows-api.md
        - operating-system/windows/windows-internals.md
        - operating-system/windows/windows-server.md
        - operating-system/windows/windows-iot.md
      - Android:
        - operating-system/android/index.md
      - FreeBSD:
        - operating-system/freebsd/index.md
      - Darwin/XNU:
        - operating-system/darwin-xnu/index.md
  - Containers:
      - containers/index.md
      - containers/docker.md
      - containers/k8s.md
      - containers/lxc.md
  - Virtualization:
      - virtualization/index.md
      - virtualization/kvm.md
      - virtualization/hyper-v.md
      - virtualization/esxi.md
      - virtualization/hosted-vm.md

  - Network:
      - network/index.md
      - Data-Communication: 
        - network/datacom/index.md
        - network/datacom/routing.md
        - network/datacom/switching.md
        - network/datacom/emulator.md
        - network/datacom/security-devices.md
        - network/datacom/certification.md
      - Protocols:
        - network/protocols/index.md
        - network/protocols/dhcp.md
        - network/protocols/ntp.md
        - network/protocols/snmp.md
      - NetDevOps:
        - network/netdevops/index.md
        - network/netdevops/network-automation.md
        - network/netdevops/sdn.md
        - network/netdevops/dpt.md
        - network/netdevops/cloud-networking.md
        - network/netdevops/nfv.md
      - Troubleshooting:
        - network/troubleshooting/index.md
      - Use-Cases:
        - network/use-cases/index.md
        - network/use-cases/enterprise-network.md
        - network/use-cases/dcn.md

  - Applications:
    - applications/index.md
    - Web-Client:
      - applications/web-client/index.md
      - applications/web-client/web-browser.md
      - applications/web-client/cli-client.md 
      - applications/web-client/client-library.md
    - Mobile:
      - applications/mobile/index.md
    - Desktop:
      - applications/desktop/index.md
      - CLI:
        - applications/desktop-client/cli/index.md
      - Cross-Platforms:
        - applications/desktop-client/cross-platforms/index.md
    - Web-Server:
      - applications/web-server/nginx.md
      - applications/web-server/apache.md
      - applications/web-server/openresty.md
      - applications/web-server/lighttpd.md
      - applications/web-server/more.md        
    - Web-Crawler:
      - applications/web-crawler/index.md
    - applications/application-server.md
    # - Application Server:
      # - applications/application-server/index.md
    #   - applications/application-server/use-cases.md
      # - applications/application-server/tomcat.md
      # - applications/application-server/jboss.md
      # - applications/application-server/django.md
      # - applications/application-server/other-application-servers.md
    - API:
      - applications/api/index.md
      - applications/api/restful.md
      - applications/api/graphql.md
      - applications/api/grpc.md
    - Protocols:
      - applications/protocols/index.md
      - applications/protocols/http-https.md
      - More Application:
        - applications/protocols/application/dns.md
        - applications/protocols/application/email.md
        - applications/protocols/application/ftp-sftp.md
        - applications/protocols/application/telnet-ssh.md
        - applications/protocols/application/ldap.md
      - Logical-Transport:
        - applications/protocols/logical-transport/index.md
        - applications/protocols/logical-transport/ssl-tls.md
        - applications/protocols/logical-transport/quic.md
        - applications/protocols/logical-transport/websockets.md
        - applications/protocols/logical-transport/webrtc.md
      - Transport:
        - applications/protocols/transport/index.md
        - applications/protocols/transport/tcp.md
        - applications/protocols/transport/udp.md
        - applications/protocols/transport/sctp.md
    - Entry:
        - applications/entry/index.md
        - applications/entry/dns.md
        - applications/entry/cdn.md
        - applications/entry/load-balancing.md
        - applications/entry/reverse-proxy.md
        - applications/entry/api-gateway.md
    - Asynchronous:
      - applications/asynchronous/index.md
      - applications/asynchronous/event-driven.md
      - applications/asynchronous/pub-sub.md
      - applications/asynchronous/message-queues.md
      - applications/asynchronous/task-queues.md
    # - Caching:
    #   - applications/caching/index.md
      # - applications/caching/in-memory-caching.md
      # - applications/caching/distributed-caching.md
    - applications/caching.md
    - applications/data-persistence.md
    
  

  - Cloud:
    - cloud/index.md
    - Cloud-Platforms:
      - cloud/cloud-platforms/index.md
      - cloud/cloud-platforms/aws.md
      - cloud/cloud-platforms/azure.md
      - cloud/cloud-platforms/gcp.md
      - cloud/cloud-platforms/alibaba-cloud.md
      - cloud/cloud-platforms/edge-cloud.md
      - cloud/cloud-platforms/private-cloud.md
    - cloud/index.md
    - DevOps:
      - cloud/devops/index.md
      - cloud/devops/cicd.md
      - cloud/devops/configuration.md
      - cloud/devops/environment.md
      - cloud/devops/iac.md
      - cloud/devops/gitops.md
      - cloud/devops/deployment-strategies.md
    - Observability:
      - cloud/observability/index.md
      - cloud/observability/monitoring.md
    - SRE:
      - cloud/sre/index.md
    - Platform-Engineering:
      - cloud/platform-engineering/index.md


  # Data-Systems
  - Data-System:
    - data-system/index.md
    - Data-Analysis:
      - data-system/data-analysis/index.md
    - Data-Visualization:
        - data-system/data-visualization/index.md
    - Data-Engineering:
      - data-system/data-engineering/index.md
      # - ETL Processes:
      #   - data-system/data-engineering/etl-processes/index.md
      # - Data Warehousing:
      #   - data-system/data-engineering/data-warehousing/index.md
      # - Data Lakes:
      #   - data-system/data-engineering/data-lakes/index.md
      # - Big Data Technologies:
      #   - data-system/data-engineering/big-data-technologies/index.md
      # - Data Pipelines:
      #   - data-system/data-engineering/data-pipelines/index.md
      # - Data Integration:
      #   - data-system/data-engineering/data-integration/index.md
      # -  Data Governance:
      #   - data-system/data-engineering/data-governance/index.md
      - DataOps:
        - data-system/data-engineering/dataops/index.md
      
  #  embedded Topic
  - Embedded:
    - embedded/index.md
    - Computer-Architecture:
      -  embedded/computer-architecture/index.md
    - Boards:
      - embedded/boards/mcu.md
      - embedded/boards/rtos.md
      - embedded/boards/sbc.md
      - embedded/boards/fpga.md
      - embedded/boards/plc.md
    - Use-Cases:
      - embedded/use-cases/index.md
      - embedded/use-cases/cyberdeck.md
      # - embedded/use-cases/iot-device.md
      # - embedded/use-cases/industrial-control.md
      # - embedded/use-cases/consumer-electronics.md
      # - embedded/use-cases/automotive-systems.md
      # - embedded/use-cases/medical-devices.md
    - Internte-of-Things:
      - embedded/iot/index.md
    - Hardware-Debugging:
      - embedded/hardware-debugging/index.md

  - IoT:
    - iot/index.md
  
  # - Cybersecurity-Matrix: https://matrix.cyberspace.bar/

plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true 

extra:
  files_server: "https://files.cyberspace.bar/cyberspace"
  # files_server: "https://files.cyberspace.bar/cyberspace-explore"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 
