# Project information
site_name: Cyberspace Explore 
use_directory_urls: true

# Repository
# repo_name: Cyberspace-Explore
# repo_url: https://github.com/AvenMay/cyberspace-explore

# Configuration
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/rocket-launch
    # repo: fontawesome/brands/github
  palette:
    - scheme: default    # 浅色模式
      # primary: indigo
      # accent: indigo
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: 切换到深色模式
    - scheme: slate      # 深色模式
      # primary: indigo
      # accent: indigo
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono

  toc:
    on_page: true
    depth: 5


# Page tree
nav:
  # - Home: index.md

  # Computer-Science Topic
  - Computer-Science: 
    - computer-science/index.md
    - Programming:
      - computer-science/programming/index.md
    - Algorithms & Data-Structures:
      - computer-science/algorithms-data-structures/index.md
      - computer-science/algorithms-data-structures/foundation.md
      - computer-science/algorithms-data-structures/advanced.md
      - computer-science/algorithms-data-structures/problem-solving-techniques.md
    - Math for CS:
      - computer-science/math-for-cs/index.md
    - Computer-Architecture:
      - computer-science/computer-architecture/index.md
    - Operating-System: 
      - computer-science/operating-system/index.md
      - Teaching-OS:
        - computer-science/operating-system/teaching-purposes/xv6.md
        - computer-science/operating-system/teaching-purposes/pintos.md
        - computer-science/operating-system/teaching-purposes/nachos.md
        - computer-science/operating-system/teaching-purposes/minix3.md
      - computer-science/operating-system/boot-process.md
      - computer-science/operating-system/experimental-os.md
    - Computer-Networking:
      - computer-science/computer-networking/index.md
    - Databases:
      - computer-science/databases/index.md
    - Languages & Compilers:
        - computer-science/compilers/index.md
    - Distributed-Systems:
      - computer-science/distributed-systems/index.md
    - Computer-Graphics:
      - computer-science/computer-graphics/index.md

  # Software-Engineering Topic
  - Software-Engineering:
    - software-engineering/index.md

    # - Software-Design:
    #   - software-engineering/software-design/index.md
    #   - software-engineering//software-design/design-patterns.md
    - Programming:
      - software-engineering/programming/index.md
      - Preparation:
        - software-engineering/programming/preparation/ranking-analysis.md
        - software-engineering/programming/preparation/encoding.md
        - software-engineering/programming/preparation/interfaces.md
        - software-engineering/programming/preparation/best-practices.md
      - Basic-Tools:
        - software-engineering/programming/basic-tools/editor.md
        - software-engineering/programming/basic-tools/git.md
      - Python:
        - software-engineering/programming/python/index.md
        - software-engineering/programming/python/use-cases.md
      - JavaScript:
        - software-engineering/programming/javascript/index.md
        - software-engineering/programming/javascript/use-cases.md
      - C:
        - software-engineering/programming/c/index.md
        - software-engineering/programming/c/use-cases.md
      - Go:
        - software-engineering/programming/go/index.md
        - software-engineering/programming/go/use-cases.md
      - Java:
        - software-engineering/programming/java/index.md
        - software-engineering/programming/java/use-cases.md
      - C#:
        - software-engineering/programming/csharp/index.md
        - software-engineering/programming/csharp/use-cases.md
      - C++:
        - software-engineering/programming/cpp/index.md
        - software-engineering/programming/cpp/use-cases.md
      - Rust:
        - software-engineering/programming/rust/index.md
        - software-engineering/programming/rust/use-cases.md


      - Assembly:
          - software-engineering/programming/assembly/index.md
          - software-engineering/programming/assembly/x86.md
          - software-engineering/programming/assembly/arm.md
          - software-engineering/programming/assembly/riscv.md
      - Platforms:
        - software-engineering/programming/platform-native/swift.md
        - software-engineering/programming/platform-native/kotlin.md
      - Functional:
        - software-engineering/programming/functional/lisp.md
        - software-engineering/programming/functional/scala.md
        - software-engineering/programming/functional/elixir.md
      - Web-First:
        - software-engineering/programming/web-first/ruby.md
        - software-engineering/programming/web-first/php.md
      - Small-Script:
        - software-engineering/programming/small-script/lua.md
        - software-engineering/programming/small-script/perl.md
      # - Zig:
      #   - software-engineering/programming/zig/index.md
      - Parallel:
        - software-engineering/programming/parallel/index.md

    - Databases:
      - software-engineering/databases/index.md
      - RDBMS:
        - software-engineering/databases/rdbms/index.md
        - software-engineering/databases/rdbms/postgresql.md
        - software-engineering/databases/rdbms/sqlite.md
        - software-engineering/databases/rdbms/mysql.md
        - software-engineering/databases/rdbms/oracle.md
        - software-engineering/databases/rdbms/sql-server.md
      - NoSQL:
        - software-engineering/databases/nosql/index.md
      - Key-Value:

        - software-engineering/databases/key-value/redis.md
        - software-engineering/databases/key-value/memcached.md
      - Document:
        - software-engineering/databases/document/mongodb.md
      - Search-Engine:
        - software-engineering/databases/search-engine/elasticsearch.md
        - software-engineering/databases/search-engine/lucene.md
        - software-engineering/databases/search-engine/solr.md
        - software-engineering/databases/search-engine/splunk.md
      - Time-Series:
        - software-engineering/databases/time-series/influxdb.md
        - software-engineering/databases/time-series/prometheus.md
      - Wide-Column:
        - software-engineering/databases/wide-column/cassandra.md
        - software-engineering/databases/wide-column/hbase.md
      - Graph:
        - software-engineering/databases/graph/neo4j.md
    - Operating-System:
        - software-engineering/operating-system/index.md
        - Basic-Tools:
          - software-engineering/operating-system/basic-tools/terminal.md
          - software-engineering/operating-system/basic-tools/ssh.md
          - software-engineering/operating-system/basic-tools/multiplexer.md
        - Unix-like:
          - software-engineering/operating-system/unix-like/index.md
        - GNU/Linux:
          - software-engineering/operating-system/gnu-linux/index.md
          - software-engineering/operating-system/gnu-linux/shell.md
          - software-engineering/operating-system/gnu-linux/gui.md
          - software-engineering/operating-system/gnu-linux/syscall.md
          - software-engineering/operating-system/gnu-linux/kernel.md
          - software-engineering/operating-system/gnu-linux/debian.md
          - software-engineering/operating-system/gnu-linux/rhel.md
          - More-Distrs:
            - software-engineering/operating-system/gnu-linux/distr/arch.md
            - software-engineering/operating-system/gnu-linux/distr/alpine.md
            - software-engineering/operating-system/gnu-linux/distr/suse.md
        - Windows:
          - software-engineering/operating-system/windows/index.md
          - software-engineering/operating-system/windows/powershell.md
          - software-engineering/operating-system/windows/gui.md
          - software-engineering/operating-system/windows/windows-api.md
          - software-engineering/operating-system/windows/windows-internals.md
          - software-engineering/operating-system/windows/windows-server.md
          - software-engineering/operating-system/windows/windows-iot.md
        - Android:
          - software-engineering/operating-system/android/index.md
        - FreeBSD:
          - software-engineering/operating-system/freebsd/index.md
        - Darwin/XNU:
          - software-engineering/operating-system/darwin-xnu/index.md
    - Containers:
        - software-engineering/containers/index.md
        - software-engineering/containers/docker.md
        - software-engineering/containers/k8s.md
        - software-engineering/containers/lxc.md
    - Virtualization:
        - software-engineering/virtualization/index.md
        - software-engineering/virtualization/kvm.md
        - software-engineering/virtualization/hyper-v.md
        - software-engineering/virtualization/esxi.md
        - software-engineering/virtualization/hosted-vm.md


  - Application-System:
    - application-system/index.md
    - Web-Client:
      - application-system/web-client/index.md
      - application-system/web-client/web-browser.md
      - application-system/web-client/cli-client.md 
      - application-system/web-client/client-library.md
    - Mobile:
      - application-system/mobile/index.md
    - Desktop:
      - application-system/desktop/index.md
      - CLI:
        - application-system/desktop-client/cli/index.md
      - Cross-Platforms:
        - application-system/desktop-client/cross-platforms/index.md
    - Web-Server:
      - application-system/web-server/nginx.md
      - application-system/web-server/apache.md
      - application-system/web-server/openresty.md
      - application-system/web-server/lighttpd.md
      - application-system/web-server/more.md        
    - Web-Crawler:
      - application-system/web-crawler/index.md
    - application-system/application-server.md
    # - Application Server:
      # - application-system/application-server/index.md
    #   - application-system/application-server/use-cases.md
      # - application-system/application-server/tomcat.md
      # - application-system/application-server/jboss.md
      # - application-system/application-server/django.md
      # - application-system/application-server/other-application-servers.md
    - API:
      - application-system/api/index.md
      - application-system/api/restful.md
      - application-system/api/graphql.md
      - application-system/api/grpc.md
    - Protocols:
      - application-system/protocols/index.md
      - application-system/protocols/http-https.md
      - More Application:
        - application-system/protocols/application/dns.md
        - application-system/protocols/application/email.md
        - application-system/protocols/application/ftp-sftp.md
        - application-system/protocols/application/telnet-ssh.md
        - application-system/protocols/application/ldap.md
      - Logical-Transport:
        - application-system/protocols/logical-transport/index.md
        - application-system/protocols/logical-transport/ssl-tls.md
        - application-system/protocols/logical-transport/quic.md
        - application-system/protocols/logical-transport/websockets.md
        - application-system/protocols/logical-transport/webrtc.md
      - Transport:
        - application-system/protocols/transport/index.md
        - application-system/protocols/transport/tcp.md
        - application-system/protocols/transport/udp.md
        - application-system/protocols/transport/sctp.md
    - Entry:
        - application-system/entry/index.md
        - application-system/entry/dns.md
        - application-system/entry/cdn.md
        - application-system/entry/load-balancing.md
        - application-system/entry/reverse-proxy.md
        - application-system/entry/api-gateway.md
    - Asynchronous:
      - application-system/asynchronous/index.md
      - application-system/asynchronous/event-driven.md
      - application-system/asynchronous/pub-sub.md
      - application-system/asynchronous/message-queues.md
      - application-system/asynchronous/task-queues.md
    # - Caching:
    #   - application-system/caching/index.md
      # - application-system/caching/in-memory-caching.md
      # - application-system/caching/distributed-caching.md
    - application-system/caching.md
    - application-system/data-persistence.md
    
  - Network-Engineering:
    - network-engineering/index.md
    - Data-Communication: 
      - network-engineering/datacom/index.md
      - network-engineering/datacom/routing.md
      - network-engineering/datacom/switching.md
      - network-engineering/datacom/emulator.md
      - network-engineering/datacom/security-devices.md
      - network-engineering/datacom/certification.md
    - Protocols:
      - network-engineering/protocols/index.md
      - network-engineering/protocols/dhcp.md
      - network-engineering/protocols/ntp.md
      - network-engineering/protocols/snmp.md
    - NetDevOps:
      - network-engineering/netdevops/index.md
      - network-engineering/netdevops/network-automation.md
      - network-engineering/netdevops/sdn.md
      - network-engineering/netdevops/dpt.md
      - network-engineering/netdevops/cloud-networking.md
      - network-engineering/netdevops/nfv.md
    - Troubleshooting:
      - network-engineering/troubleshooting/index.md
    - Use-Cases:
      - network-engineering/use-cases/index.md
      - network-engineering/use-cases/enterprise-network.md
      - network-engineering/use-cases/dcn.md

  - Infrastructure/Cloud:
    - infrastructure/index.md
    - Cloud-Platforms:
      - infrastructure/cloud-platforms/index.md
      - infrastructure/cloud-platforms/aws.md
      - infrastructure/cloud-platforms/azure.md
      - infrastructure/cloud-platforms/gcp.md
      - infrastructure/cloud-platforms/alibaba-cloud.md
      - infrastructure/cloud-platforms/edge-cloud.md
      - infrastructure/cloud-platforms/private-cloud.md
    - infrastructure/index.md
    - DevOps:
      - infrastructure/devops/index.md
      - infrastructure/devops/cicd.md
      - infrastructure/devops/configuration.md
      - infrastructure/devops/environment.md
      - infrastructure/devops/iac.md
      - infrastructure/devops/gitops.md
      - infrastructure/devops/deployment-strategies.md
    - Observability:
      - infrastructure/observability/index.md
      - infrastructure/observability/monitoring.md
    - SRE:
      - infrastructure/sre/index.md
    - Platform-Engineering:
      - infrastructure/platform-engineering/index.md


  # Data-Systems
  - Data-System:
    - data-system/index.md
    - Data-Analysis:
      - data-system/data-analysis/index.md
    - Data-Visualization:
        - data-system/data-visualization/index.md
    - Data-Engineering:
      - data-system/data-engineering/index.md
      # - ETL Processes:
      #   - data-system/data-engineering/etl-processes/index.md
      # - Data Warehousing:
      #   - data-system/data-engineering/data-warehousing/index.md
      # - Data Lakes:
      #   - data-system/data-engineering/data-lakes/index.md
      # - Big Data Technologies:
      #   - data-system/data-engineering/big-data-technologies/index.md
      # - Data Pipelines:
      #   - data-system/data-engineering/data-pipelines/index.md
      # - Data Integration:
      #   - data-system/data-engineering/data-integration/index.md
      # -  Data Governance:
      #   - data-system/data-engineering/data-governance/index.md
      - DataOps:
        - data-system/data-engineering/dataops/index.md
      
  #  Embedded-System Topic
  - Embedded-System:
    - embedded-system/index.md
    - Computer-Architecture:
      -  embedded-system/computer-architecture/index.md
    - Boards:
      - embedded-system/boards/mcu.md
      - embedded-system/boards/rtos.md
      - embedded-system/boards/sbc.md
      - embedded-system/boards/fpga.md
      - embedded-system/boards/plc.md
    - Use-Cases:
      - embedded-system/use-cases/index.md
      - embedded-system/use-cases/cyberdeck.md
      # - embedded-system/use-cases/iot-device.md
      # - embedded-system/use-cases/industrial-control.md
      # - embedded-system/use-cases/consumer-electronics.md
      # - embedded-system/use-cases/automotive-systems.md
      # - embedded-system/use-cases/medical-devices.md
    - Internte-of-Things:
      - embedded-system/iot/index.md
    - Hardware-Debugging:
      - embedded-system/hardware-debugging/index.md

  - IoT:
    - iot/index.md
  
  - Cybersecurity-Matrix: https://matrix.cyberspace.bar/

plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true 

extra:
  files_server: "https://files.cyberspace.bar/cyberspace"
  # files_server: "https://files.cyberspace.bar/cyberspace-explore"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 
